[project]
name = "strembox-plugin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.5",
    "asyncpg>=0.31.0",
    "bencode2>=0.3.30",
    "fastapi[standard]>=0.135.3",
    "jinja2>=3.1.6",
    "pydantic-settings>=2.15.0",
    "redis>=8.1.0",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"

[dependency-groups]
dev = [
    "aioresponses>=0.7.9",
    "pytest>=9",
    "pytest-asyncio>=1",
    "ruff>=0.16.7",
    "ty>=0.0.81",
]
